### ISSUE TITLE
notebook files are not present in the repo anymore

### ISSUE THREAD

**Issue by kephale** [napari/napari-workshop-template#13]
The workshop instructions imply that there should be notebook files available in this repository (e.g. here: https://napari.org/napari-workshop-template/notebook_setup.html)

However, it looks like we only have the rendered outputs of notebook files now.

**Comment by kephale** [comment]
Oh my goodness, they are jupytext notebooks. @melissawm pointed this out to me!

**Comment by melissawm** [comment]
I think we may need to be more explicit about this in the docs, there are still a few places where we mention ipynb files, but yes - md files are much easier to diff!
