### ISSUE TITLE
copyright year is incorrect

### ISSUE THREAD

**Issue by kephale** [napari/napari-workshop-template#16]
I created a template using this repository (recently and within the year `2023`) and the rendered outputs display `2022` as the copyright year at the bottom of the page https://kephale.github.io/napari-workshop-mandm-2023/home.html. 

<img width="404" alt="image" src="https://github.com/napari/napari-workshop-template/assets/400105/53476013-bf30-44c9-94f1-b14c7435bee8">

**Comment by melissawm** [comment]
There have been long discussions on different projects about this coyright notice - see for example https://hynek.me/til/copyright-years/

Should we add a note that when you fork the repo you should update the copyright year for your own materials? Or do we want to do that automatically somehow?

**Comment by jni** [comment]
@melissawm [this post](https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/) linked from Hynek's suggests dropping the year altogether, so let's just do that?
