### ISSUE TITLE
[Bug] Only first nbscreenshot is shown

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari-workshop-template#21]
I noticed on the GitHub Pages site where the notebooks are rendered, only the first nbscreenshot seems to appear.
E.g. Go to: https://napari.org/napari-workshop-template/notebooks/intro_bioimage_visualization.html#color-channels-and-blending
Then look up to see a cell with just `nbscreenshot` or scroll down to see other cells with just `nbscreenshot`

**Comment by melissawm** [comment]
It's fixed now, thanks @psobolewskiPhD :D
