### ISSUE TITLE
Mental note: check out jupyterlab_myst

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari-workshop-template#25]
As the title says, using jupyterlab_myst could allow for the nicer admonitions and things in the rendered HTML notebooks, while not looking too bad in notebooks opened in jupyterlab.
https://github.com/executablebooks/jupyterlab-myst

**Comment by brisvag** [comment]
This is very much not mental :rofl:

**Comment by melissawm** [comment]
oh wow, I had not seen this, cool stuff! Thanks @psobolewskiPhD !

**Comment by psobolewskiPhD** [comment]
I installed this into my workshop env and ItJustWorks!
Here's a notebook in jupyterlab (open as notebook):
<img width="1729" alt="image" src="https://github.com/napari/napari-workshop-template/assets/76622105/7a522fd5-b6fc-4df8-b92c-0e1fb857f037">

No package on conda-forge, but pip install works.

**Comment by psobolewskiPhD** [comment]
I think I will add this to the `download the notebooks and run locally` section and the binder stuff when I port over some of my recent wokrshop materials, because I used admonitions in the notebooks.
