### ISSUE TITLE
Binder rendering not working

### ISSUE THREAD

**Issue by dgmccart** [napari/napari-workshop-template#8]
The option to open the notebook in binder isn't present on the template juypter books website, and using the link directly in the repo redirects to an error page (screenshots attached).
<img width="1112" alt="Screenshot 2022-12-02 at 2 06 50 PM" src="https://user-images.githubusercontent.com/92180364/205399401-1eb631c8-0e23-4a03-858f-4766fa294452.png">
<img width="983" alt="Screenshot 2022-12-02 at 2 08 03 PM" src="https://user-images.githubusercontent.com/92180364/205399405-05ec2916-6ec3-4801-89d4-439f9874e663.png">

**Comment by melissawm** [comment]
Hi @dgmccart - the current rendered documentation url should be

https://napari.github.io/napari-workshop-template

(see #7 ). In there, if you go to any notebook you can see the binder link. I am also updating the link in the readme to point to the right place - thanks for opening the issue!

**Comment by psobolewskiPhD** [comment]
I'm going to close this, binder is super slow but has been working for me.
